In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("newsgroups_train.csv")
df.head(5)

text  target       category
0  From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2  From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3  From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4  From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space

In [33]:
df.text

0       From: degroff@netcom.com (21012d)\nSubject: Re...
1       From: ab@nova.cc.purdue.edu (Allen B)\nSubject...
2       From: healta@saturn.wwc.edu (Tammy R Healy)\nS...
3       From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...
4       From: henry@zoo.toronto.edu (Henry Spencer)\nS...
                              ...                        
1652    From: ab@nova.cc.purdue.edu (Allen B)\nSubject...
1653    From: renes@ecpdsharmony.cern.ch (Rene S. Dutc...
1654    From: xrcjd@resolve.gsfc.nasa.gov (Charles J. ...
1655    From: dietz@cs.rochester.edu (Paul Dietz)\nSub...
1656    From: jhwitten@cs.ruu.nl (Jurriaan Wittenberg)...
Name: text, Length: 1657, dtype: object

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
vectorize = CountVectorizer(max_features=1500)
vectors = vectorize.fit_transform(df['text'])
vectors = vectors.toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
for vec in vectors[0]:
    print(vec, end=" ")

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [12]:
vectors.shape

(1657, 1500)

In [13]:
X = vectors
y = df.target

In [16]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

(X_train,X_test,y_train)

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 2, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 1425    0
 319     1
 452     1
 1364    1
 1110    1
        ..
 835     1
 1216    1
 1653    1
 559     0
 684     1
 Name: target, Length: 1325, dtype: int64)

In [75]:
model = MultinomialNB()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

predictions

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0, 2, 1, 1,
       1, 2, 2, 1, 2, 1, 1, 0, 1, 2, 1, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 2,
       1, 0, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 1, 2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0,
       1, 2, 2, 1, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 2, 1, 2, 0,
       1, 2, 2, 1, 0, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 2, 1, 1, 0, 2, 2, 1, 1, 2, 0, 0, 2, 2, 0, 0, 1, 1, 0,
       2, 1, 0, 1, 0, 2, 0, 2, 2, 1, 1, 2, 0, 2, 1, 1, 1, 0, 2, 1, 1, 0,
       1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 0, 0, 2, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 2, 1, 0, 2, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0, 2, 1,
       0, 2, 0, 2, 2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 2, 1, 2,
       2, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 2, 2, 0, 1,
       1, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 0, 2, 1, 1, 0, 2, 1, 2, 2,
       1, 0, 2, 2, 0, 1, 1, 1, 1, 0, 1, 2, 2, 0, 2,

In [72]:
df.target.unique()

array([2, 1, 0])

In [71]:
ls = {0: "alt.atheism",1:"comp.graphics",2:"sci.space"}
ls

{0: 'alt.atheism', 1: 'comp.graphics', 2: 'sci.space'}

In [80]:
# Assuming y_test and predictions are iterables of the same length
for y, pred in zip(y_test, predictions):
    print(f"y_test: {y}, category: {ls.get(y)}, pred_target : {pred},  predictions: {ls.get(pred)}")

y_test: 1, category: comp.graphics, pred_target : 1,  predictions: comp.graphics
y_test: 1, category: comp.graphics, pred_target : 1,  predictions: comp.graphics
y_test: 1, category: comp.graphics, pred_target : 1,  predictions: comp.graphics
y_test: 2, category: sci.space, pred_target : 1,  predictions: comp.graphics
y_test: 1, category: comp.graphics, pred_target : 1,  predictions: comp.graphics
y_test: 1, category: comp.graphics, pred_target : 1,  predictions: comp.graphics
y_test: 1, category: comp.graphics, pred_target : 1,  predictions: comp.graphics
y_test: 0, category: alt.atheism, pred_target : 0,  predictions: alt.atheism
y_test: 1, category: comp.graphics, pred_target : 1,  predictions: comp.graphics
y_test: 2, category: sci.space, pred_target : 2,  predictions: sci.space
y_test: 0, category: alt.atheism, pred_target : 0,  predictions: alt.atheism
y_test: 0, category: alt.atheism, pred_target : 0,  predictions: alt.atheism
y_test: 0, category: alt.atheism, pred_target : 0,  

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm = confusion_matrix(y_test,predictions)
cm

array([[ 99,   1,   2],
       [  3, 108,   2],
       [  3,   4, 110]])

In [32]:
cr = classification_report(y_test,predictions)
print(f"cr: {cr}")
accuracy = accuracy_score(y_test,predictions)
print(f"accuracy: {accuracy}")

cr:               precision    recall  f1-score   support

           0       0.94      0.97      0.96       102
           1       0.96      0.96      0.96       113
           2       0.96      0.94      0.95       117

    accuracy                           0.95       332
   macro avg       0.95      0.96      0.95       332
weighted avg       0.96      0.95      0.95       332

accuracy: 0.9548192771084337
